CREATE TABLE tb_contract (
	id MEDIUMINT AUTO_INCREMENT NOT NULL,
	total_cash_value BIGINT,
	cpf_cnpj VARCHAR(14) NOT NULL UNIQUE,
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_date TIMESTAMP,
	result INT NOT NULL,
	PRIMARY KEY (id)
);



